services:
  - type: web
    name: color-fix-match
    env: python
    plan: free
    region: frankfurt
    branch: main
    root: color-fix-match

    runtime:
      pythonVersion: "3.12.3"   # full version required

    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt

    startCommand: python server.py

    envVars:
      - key: FLASK_ENV
        value: production

    ports:
      - port: 8000
        protocol: http

    autoDeploy: true
