services:
  - type: web
    name: color-fix-match
    env: python
    plan: free
    region: frankfurt
    branch: main
    root: color-fix-match
    pythonVersion: 3.10
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: production
    ports:
      - 8000
    autoDeploy: true