services:
  - type: web
    name: color-detector
    env: python
    pythonVersion: 3.10.14
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: MY_SECRET_KEY
        value: my-secret-value